### ISSUE TITLE
su erro

### ISSUE THREAD

**Issue by blurry-face12** [agnostic-apollo/sudo#3]
when i execute this command："sudo dockerd --iptables=false"
it prompt：
allowed
usage: su [UID[,GID[,GID2]...]] [COMAND [ARG...]]

Switch to WHO (default 'root') and run the given command (default sh) .

where WHO is a comma-separated list of user，group，

and supplementary groups in that order

NO 'su’ binary found that supports the ' --shell', ' --preserve -environment' and ' --mount-master' options

sudo requires a 'su' binary that supports the ' --shell', '--preserve - environment' and ' --mount-master’options

how can i solve it？

**Comment by agnostic-apollo** [comment]
Install Magisk on your device, android system provided `su` binary will not work, it is very limited and doesn't support `-c` option either.

- https://github.com/topjohnwu/Magisk
- https://cs.android.com/android/platform/superproject/main/+/main:system/extras/su/su.cpp

**Comment by blurry-face12** [comment]
> Install Magisk on your device, android system provided `su` binary will not work, it is very limited and doesn't support `-c` option either.
> 
> * https://github.com/topjohnwu/Magisk
> * https://cs.android.com/android/platform/superproject/main/+/main:system/extras/su/su.cpp
thank you for your answer
you mean we want use “sudo”, must install Magisk, use it replace android system provided su? 
but i don‘t see install magisk step on your README

**Comment by agnostic-apollo** [comment]
Yeah, currently it is not there, but I have added docs for it locally, will be updated soon.

You necessarily don't need Magisk, there are other root managers as well, whose binaries provide all the required options,  like [SuperSU](https://su.chainfire.eu/) but it doesn't support latest android versions. Point is that, android system provided `su` will not work for `sudo` or `tsu`. Most people root their phones with Magisk these days, and SuperSU was used in the old era.

- https://su.chainfire.eu

**Comment by blurry-face12** [comment]
> Yeah, currently it is not there, but I have added docs for it locally, will be updated soon.
> 
> You necessarily don't need Magisk, there are other root managers as well, whose binaries provide all the required options, like [SuperSU](https://su.chainfire.eu/) but it doesn't support latest android versions. Point is that, android system provided `su` will not work for `sudo` or `tsu`. Most people root their phones with Magisk these days, and SuperSU was used in the old era.
> 
> * https://su.chainfire.eu

Thank you for your reminder!
I will try again later
